# Generated by Django 4.2.2 on 2024-10-19 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_apartment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Apartment',
        ),
    ]
