# Generated by Django 4.2.2 on 2024-10-19 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_apartment_calendar_booking_apartment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apartment',
            name='max_guests',
        ),
        migrations.AddField(
            model_name='apartment',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='apartment',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='apartment',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
